org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.07
minecraft_version=1.21
minecraft_version_range=[1.21,1.21.1)
neo_version=21.0.143
neo_version_range=[21.0.143,)
loader_version_range=[4,)

mod_id=configjs
mod_name=ConfigJS
mod_license=MIT
mod_version=2.0.0-alpha
mod_group_id=com.notenoughmail.configjs
mod_authors=NotEnoughMail
mod_description=Write custom toml config files through KubeJS
mixin_version=0.8.5

kube_version_range=[2001.6.3-build.83,)

# Kube
kubejs_version=2100.7.0-build.116

# Nicities
jei_version=5567933
jade_version=5572926
probejs_version=5536459